name: publish

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: webmaster
          POSTGRES_PASSWORD: test
          POSTGRES_DB: betforge
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run migrations
        run: ./gradlew migrationsMigrate -Dbetforge.jdbc.url=jdbc:postgresql://localhost:5432/betforge -Dbetforge.jdbc.user=webmaster -Dbetforge.jdbc.password=test -Dbetforge.applications.admin.username=test -Dbetforge.applications.admin.password=test
      - name: Run tests
        run: ./gradlew test -Dbetforge.jdbc.url=jdbc:postgresql://localhost:5432/betforge -Dbetforge.jdbc.user=webmaster -Dbetforge.jdbc.password=test -Dbetforge.applications.admin.username=test -Dbetforge.applications.admin.password=test
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
      - name: Publish to the Github packages
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  clean:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          keep: 2
          names: |
            dev.tmsoft.kotlin.common-lib
